highlighter:   'rouge'
permalink:    /:year-:month-:day/:title/
exclude:      ["WE-settings.xml", "SLaks.Blog.sln", "SLaks.Blog.v11.suo", "CNAME", "*.ide", "node_modules"]

port:        8775

excerpt_separator: ""   # Workaround for https://github.com/mojombo/jekyll/issues/1401

kramdown:
  input: GFM

githubRawUrl: https://raw.github.com/SLaks/SLaks.Blog/gh-pages/
githubUrl:    https://github.com/SLaks/SLaks.Blog/tree/gh-pages/

absoluteBaseUrl: http://blog.slaks.net

gems:
  - jekyll-redirect-from
